# Generated by Django 4.0.3 on 2022-04-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
