# Generated by Django 4.0.2 on 2022-05-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodel',
            name='close',
            field=models.BooleanField(default=False),
        ),
    ]
