# Generated by Django 4.0.3 on 2022-05-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_requestmodel_close'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoveBan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
